layout_spectrum: 0.8283751306589693
typography_spectrum: 0.6786375558003783
color:
  brandStrength: 0.010513480054214597
  lightness: 0.7416171294171363
  saturation: 0.18911650474183261
  rhythmicContrast: 0.7162118391133845
  brandColors:
    - '#7A8DA0'
    - '#374958'
    - '#CCDDEE'
    - '#F17256'
    - '#000000'
name: Oficinas IBS
